core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('confirm_your_email', views.ConfirmEmailView.as_view(), name='confirm_email'),
    path('activate/<uidb64>/<token>', views.ActivateView.as_view(), name='activate'),
    path(
        'activate/successful/',
        views.ActivateSuccuessfulView.as_view(),
        name='activate_successful',
    ),
]

jobportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('portal.urls')),
    path('', include('pages.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

portal/urls.py
from django.urls import path
from . import views


app_name = 'portal'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/jobcandidate/create', views.JobCandidateProfileCreateView.as_view(), name='jobcandidate_create'),
    path('profile/jobcandidate/<int:pk>/update', views.JobCandidateProfileUpdateView.as_view(), name='jobcandidate_update'),
    path('profile/employer/create', views.EmployerProfileCreateView.as_view(), name='employer_create'),
    path('profile/employer/<int:pk>/update', views.EmployerProfileUpdateView.as_view(), name='employer_update'),
]

portal/models.py
from django.db import models
from django.contrib.auth import get_user_model


class JobCandidate(models.Model):
    birth_date = models.DateField(blank=True, null=True)
    short_bio = models.CharField(max_length=150, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    user = models.OneToOneField(
        get_user_model(), primary_key=True, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Job Candidate'
        verbose_name_plural = 'Job Candidates'

    def __str__(self):
        return f'{self.user.username} | {self.user.first_name} {self.user.last_name}'
    

class Employer(models.Model):
    short_bio = models.CharField(max_length=150, blank=True, null=True)
    user = models.OneToOneField(
        get_user_model(), primary_key=True, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = 'Employer'
        verbose_name_plural = 'Employers'

    def __str__(self):
        return f'{self.user.username} | {self.user.first_name} {self.user.last_name}'


class Company(models.Model):
    title = models.CharField(max_length=100, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    manager = models.ForeignKey(Employer, on_delete=models.CASCADE, related_name='companies')

    class Meta:
        verbose_name = 'Company'
        verbose_name_plural = 'Companies'

    def __str__(self):
        return self.title
    

class JobCategory(models.Model):
    name = models.CharField(max_length=50, blank=False, null=False, unique=True)

    class Meta:
        verbose_name = 'Job Category'
        verbose_name_plural = 'Job Categories'

    def __str__(self):
        return self.name


class Job(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    category = models.ForeignKey(JobCategory, on_delete=models.PROTECT, related_name='jobs')
    company = models.ForeignKey(
        Company, on_delete=models.CASCADE, related_name='jobs')
    
    class Meta:
        permissions = [('can_post_jobs', 'Can add new job posts')]
        verbose_name = 'Job'
        verbose_name_plural = 'Jobs'

    def __str__(self):
        return f'{self.title} | {self.company.title}'


class JobApplication(models.Model):
    STATUS_APPROVED = 'approved'
    STATUS_PENDING = 'pending'
    STATUS_REJECTED = 'rejected'
    STATUS_CHOICES = [
        (STATUS_APPROVED, 'Approved'),
        (STATUS_PENDING, 'Pending'),
        (STATUS_REJECTED, 'Rejected'),
    ]
    job = models.ForeignKey(Job, on_delete=models.PROTECT,
                            related_name='applications')
    candidate = models.ForeignKey(
        JobCandidate, on_delete=models.CASCADE, related_name='job_applications')
    submition_date = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default=STATUS_PENDING)
    message = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = 'Job Application'
        verbose_name_plural = 'Job Applications'

    def __str__(self):
        return str(self.pk)

    def clean(self):
        from django.core.exceptions import ValidationError
        if self.status != self.STATUS_PENDING and not self.message:
            raise ValidationError(message='Message is required.')
        return super().clean()

portal/forms.py
from django import forms
from . import models


class DateInput(forms.DateInput):
    input_type = 'date'


class JobCandidateProfileForm(forms.ModelForm):
    
    class Meta:
        model = models.JobCandidate
        fields = ['birth_date', 'short_bio', 'description']
        widgets = {
            'birth_date': DateInput()
        }


class EmployerProfileForm(forms.ModelForm):

    class Meta:
        model = models.Employer
        fields = ['short_bio']

portal/views.py
from django.views.generic import TemplateView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from . import forms
from . import models


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'portal/profile.html'


class JobCandidateProfileCreateView(LoginRequiredMixin, FormView):
    form_class = forms.JobCandidateProfileForm
    success_url = reverse_lazy('portal:profile')
    template_name = 'portal/jobcandidate_profile_form.html'

    def form_valid(self, form):
        models.JobCandidate(
            birth_date=form.cleaned_data['birth_date'].isoformat() if form.cleaned_data.get('birth_date', None) else None,
            short_bio=form.cleaned_data['short_bio'],
            description=form.cleaned_data['description'],
            user=self.request.user
        ).save()
        return super(JobCandidateProfileCreateView, self).form_valid(form)


class JobCandidateProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = forms.JobCandidateProfileForm
    model = models.JobCandidate
    success_url = reverse_lazy('portal:profile')
    template_name = 'portal/jobcandidate_profile_form.html'


class EmployerProfileCreateView(LoginRequiredMixin, FormView):
    form_class = forms.EmployerProfileForm
    model = models.Employer
    success_url = reverse_lazy('portal:profile')
    template_name = 'portal/employer_profile_form.html'

    def form_valid(self, form):
        models.Employer(
            short_bio=form.cleaned_data['short_bio'],
            user=self.request.user
        ).save()
        return super().form_valid(form)


class EmployerProfileUpdateView(LoginRequiredMixin, UpdateView):
    form_class = forms.EmployerProfileForm
    model = models.Employer
    success_url = reverse_lazy('portal:profile')
    template_name = 'portal/employer_profile_form.html'

templates/portal/employer_profile_form.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" class="d-flex align-items-center flex-column">
                {% csrf_token %}
                {% for field in form %}
                {% if field.value %}
                <input placeholder="{{ field.label }}" class="form-control mb-2" name="{{ field.html_name }}"
                    id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}" value="{{ field.value }}">
                {% else %}
                <input placeholder="{{ field.label }}" class="form-control mb-2" name="{{ field.html_name }}"
                    id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}">
                {% endif %}
                {% for error in field.errors %}
                <p class="text-danger font-monospace">{{ error }}</p>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <p class="text-danger font-monospace">{{ error }}</p>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Save">
            </form>
        </div>
    </div>
</div>
{% endblock main %}

templates/portal/jobcandidate_profile_form.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" class="d-flex align-items-center flex-column">
                {% csrf_token %}
                {% for field in form %}
                {% if field.value %}
                <input placeholder="{{ field.label }}" class="form-control mb-2" name="{{ field.html_name }}"
                    id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}" value="{{ field.value }}">
                {% else %}
                <input placeholder="{{ field.label }}" class="form-control mb-2" name="{{ field.html_name }}"
                    id="{{ field.id_for_label }}" type="{{ field.field.widget.input_type }}">
                {% endif %}
                {% for error in field.errors %}
                <p class="text-danger font-monospace">{{ error }}</p>
                {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                <p class="text-danger font-monospace">{{ error }}</p>
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Save">
            </form>
        </div>
    </div>
</div>
{% endblock main %}

templates/portal/profile.html
{% extends 'base.html' %}
{% block main %}
<div class="container">
    <div class="row">
        
        <div class="col-12">
            <h2>General Information</h2>
        </div>
        <div class="col-12">Username: {{ user.username }}</div>
       
        <div class="col-12">Email: {{ user.email }}</div>
        
        <div class="col-12 pb-3 mb-4 border-bottom">Full Name:
        {% if not user.first_name and not user.last_name %}
        not specified
        {% else %}
        {{ user.first_name }}{{ user.last_name }}
        {% endif %}
        </div>

        {% if user.jobcandidate %}
        <div class="col-12">
            <h2>User Profile <a href="{% url 'portal:jobcandidate_update' user.jobcandidate.pk %}" class="btn btn-primary">Edit</a></h2>
            <p>This profile will be shown as your resume to empolyers.</p>
        </div>

        <div class="col-lg-6">Birth Date:
        {% if not user.jobcandidate.birth_date %}
        not specified
        {% else %}
        {{ user.jobcandidate.birth_date }}
        {% endif %}
        </div>

        <div class="col-6">Short Bio:
        {% if not user.jobcandidate.short_bio %}
        not specified
        {% else %}
        {{ user.jobcandidate.short_bio }}
        {% endif %}
        </div>

        <div class="col-12 pb-3 mb-4 border-bottom">Description:
        {% if not user.jobcandidate.description %}
        not specified
        {% else %}
        {{ user.jobcandidate.description }}
        {% endif %}
        </div>
        {% else %}
        <div class="col-12 pb-3 mb-4 border-bottom">
            <div class="alert alert-warning" role="alert">
                You have no job candidate profile. <a href="{% url 'portal:jobcandidate_create' %}">Create now!</a>
            </div>              
        </div>
        {% endif %}

        {% if user.employer %}
        <div class="col-12">
            <h2>Employer Profile <a href="{% url 'portal:employer_update' user.employer.pk %}" class="btn btn-primary">Edit</a></h2>
            <p>This profile will be shown as your profile to job candidates.</p>
        </div>

        <div class="col-12">Short Bio:
        {% if not user.employer.short_bio %}
        not specified
        {% else %}
        {{ user.employer.short_bio }}
        {% endif %}
        </div>
        {% else %}
        <div class="col-12">
            <div class="alert alert-warning" role="alert">
                You have no employer profile. <a href="{% url 'portal:employer_create' %}">Create now!</a>
            </div>              
        </div>
        {% endif %}
    </div>
</div>
{% endblock main %}