core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('confirm_your_email', views.ConfirmEmailView.as_view(), name='confirm_email'),
    path('activate/<uidb64>/<token>', views.ActivateView.as_view(), name='activate'),
    path(
        'activate/successful/',
        views.ActivateSuccuessfulView.as_view(),
        name='activate_successful',
    ),
]

jobportal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('portal.urls')),
    path('', include('pages.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]

pages/urls.py
from django.urls import path
from . import views


app_name = 'pages'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
]

portal/urls.py
from django.urls import path
from . import views


app_name = 'portal'
urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/jobcandidate/create', views.JobCandidateProfileCreateView.as_view(), name='jobcandidate_create'),
    path('profile/jobcandidate/<int:pk>/update', views.JobCandidateProfileUpdateView.as_view(), name='jobcandidate_update'),
    path('profile/employer/create', views.EmployerProfileCreateView.as_view(), name='employer_create'),
    path('profile/employer/<int:pk>/update', views.EmployerProfileUpdateView.as_view(), name='employer_update'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Job Portal{% endblock title %}</title>
</head>

<body>
    {% block navbar %}
    <div class="container">
        <header
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <div class="col-md-3 mb-2 mb-md-0">
                <a href="/" class="d-inline-flex link-body-emphasis text-decoration-none">
                    <svg class="bi" width="40" height="32" role="img" aria-label="Bootstrap">
                        <use xlink:href="#bootstrap"></use>
                    </svg>
                </a>
            </div>

            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'pages:home' %}" class="nav-link px-2 link-secondary">Home</a></li>
                <li><a href="#" class="nav-link px-2">About</a></li>
            </ul>

            <div class="col-md-3 text-end">
                {% if user.is_authenticated %}
                <div class="dropdown">
                    <button class="btn btn-outline-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Account
                    </button>
                    <ul class="dropdown-menu">
                        <li><h6 class="dropdown-header">@{{ user.username }}</h6></li>
                        <li><a class="dropdown-item" href="{% url 'portal:profile' %}">Profile</a></li>
                        <li><a class="dropdown-item" href="#">Job Applications</a></li>
                        <li><a class="dropdown-item" href="#">Messages</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Settings</a></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                      </ul>
                  </div>
          
                {% else %}
                    <a href="{% url 'login' %}" type="button" class="btn btn-outline-primary me-2">Login</a>
                    <a href="{% url 'signup' %}" type="button" class="btn btn-primary">Sign-up</a>
                {% endif %}
            </div>
        </header>
    </div>
    {% endblock navbar %}
    <main>
        {% block main %}
        {% endblock main %}
    </main>
    <footer>
        {% block footer %}
        <div class="container">
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <div class="col-md-4 d-flex align-items-center">
                    <span class="mb-3 mb-md-0 text-body-secondary">All rights reserved</span>
                </div>
            </footer>
        </div>
        {% endblock footer %}
    </footer>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>